name: release-pipeline
on:
  push:
    tags:
      - "*"
env:
  DOCKER_REPO: dev.docker.ascendise.ch/ascendise/tollkeeper

jobs:
  assert-cargo-version:
    runs-on: ubuntu-latest
    container: 
      image: docker.ascendise.ch/ascendise/cargo-runner:1.1.0-rust1.92
      credentials:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Assert app/Cargo.toml version matches current tag
        run: |
          app_version=$(cargo metadata --format-version=1 --no-deps --manifest-path='./app/Cargo.toml' | jq -r '.packages[0].version')
          echo "app/Cargo.toml Version: $app_version"
          echo "Git tag: ${{gitea.ref_name}}"
          if [ $app_version != ${{gitea.ref_name}} ]; then
            echo "Tags do not match! Change version in app/Cargo.toml and/or retag to release!" 1>&2
            exit 1
          fi  
          echo "All good!"
  docker-push:
    needs: [assert-cargo-version]
    env:
      VERSION_TAG: ${{env.DOCKER_REPO}}:${{gitea.ref_name}}
      STABLE_TAG: ${{env.DOCKER_REPO}}:stable
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Registry
        run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASS}} dev.docker.ascendise.ch
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Build docker image
        run: docker build . -t $VERSION_TAG -t $STABLE_TAG
      - name: Push docker image
        run: docker push $VERSION_TAG 
      - name: Push stable tag
        run: |
          if [[ ${{gitea.ref_name}} =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            docker push $STABLE_TAG
          else
            echo "Not a full release. Not pushing stable tag"
          fi
