name: test-pipeline
on:
  pull_request:
    branches: [main, release/*] 

jobs:
  cargo-test:
    env:
      RUNNER_TOOL_CACHE: $HOME/.cargo/
    runs-on: ubuntu-latest
    container: 
      image: docker.ascendise.ch/ascendise/cargo-runner:1.1.0-rust1.92
      credentials:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Run cargo test
        run: cargo test 
  cargo-clippy:
    runs-on: ubuntu-latest
    container: 
      image: docker.ascendise.ch/ascendise/cargo-runner:1.1.0-rust1.92
      credentials:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Run cargo clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
  cargo-fmt:
    runs-on: ubuntu-latest
    container: 
      image: docker.ascendise.ch/ascendise/cargo-runner:1.1.0-rust1.92
      credentials:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Run cargo fmt
        run: cargo fmt --all --check
  docker-build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: docker build (Dry-Run)
        run: docker build --build-arg "BUILDKIT_DOCKERFILE_CHECK=error=true" .
