FROM rust:1.92-alpine AS build

WORKDIR /usr/src/tollkeeper
COPY . .
RUN --mount=type=cache,target=target \
  --mount=type=cache,target=/usr/local/cargo/git/db \
  --mount=type=cache,target=/usr/local/cargo/registry \
  cargo install --path app
RUN cp -r ./app/templates /usr/local/cargo/bin/

FROM nginxdemos/hello:latest
WORKDIR /usr/local/bin/
COPY --from=build /usr/src/tollkeeper/proxy_test/start_env.sh app/start_env.sh
COPY --from=build /usr/src/tollkeeper/app/config.toml app/config.toml
COPY --from=build /usr/local/cargo/bin/app tollkeeper
RUN chmod u+x ./app/start_env.sh
CMD ["./app/start_env.sh"]
