use super::*;

/// [Declaration] for Hashcash-style challenges [tolls](Toll)
///
/// See <http://hashcash.org> for more information
pub struct HashcashDeclaration {}

impl Declaration for HashcashDeclaration {
    fn declare(&self, suspect: Suspect, order_id: OrderIdentifier) -> Toll {
        todo!()
    }

    fn pay(&self, payment: &Payment, suspect: &Suspect) -> Result<Visa, InvalidPaymentError> {
        todo!()
    }
}

pub struct Stamp {
    ver: u8,
    bits: u8,
    date: Timestamp,
    resource: String,
    ext: Extension,
    rand: String,
    counter: String,
}

impl Stamp {
    /// Stamp format version. Currently 1 is expected
    /// Fuck me if there is a new stamp format
    pub fn ver(&self) -> u8 {
        self.ver
    }

    /// Number of zero bits the hash has to start with.
    pub fn bits(&self) -> u8 {
        self.bits
    }

    /// ```YYMMDDhhmmss``` format date the stamp was created at. Used for expiry check
    pub fn date(&self) -> &Timestamp {
        &self.date
    }

    /// Resource the stamp is minted for
    pub fn resource(&self) -> &str {
        &self.resource
    }

    /// Extension field used by tollkeeper
    pub fn ext(&self) -> &Extension {
        &self.ext
    }

    /// string of random characters to avoid preimage attacks
    pub fn rand(&self) -> &str {
        &self.rand
    }

    /// string generated by user to get the required amount of bits
    pub fn counter(&self) -> &str {
        &self.counter
    }
}

pub struct Timestamp {}
pub struct Extension {}
