#[cfg(test)]
mod tests;

use super::*;

/// [Declaration] for Hashcash-style challenges [tolls](Toll)
///
/// See <http://hashcash.org> for more information
pub struct HashcashDeclaration {}

impl Declaration for HashcashDeclaration {
    fn declare(&self, suspect: Suspect, order_id: OrderIdentifier) -> Toll {
        todo!()
    }

    fn pay(&self, payment: &Payment, suspect: &Suspect) -> Result<Visa, InvalidPaymentError> {
        todo!()
    }
}

struct Stamp {
    ver: u8,
    bits: u8,
    date: Timestamp,
    resource: String,
    ext: Extension,
    rand: String,
    counter: String,
}

impl Stamp {
    fn new(
        ver: u8,
        bits: u8,
        date: Timestamp,
        resource: impl Into<String>,
        ext: Extension,
        rand: impl Into<String>,
        counter: impl Into<String>,
    ) -> Self {
        Self {
            ver,
            bits,
            date,
            resource: resource.into(),
            ext,
            rand: rand.into(),
            counter: counter.into(),
        }
    }

    fn empty(
        ver: u8,
        bits: u8,
        date: Timestamp,
        resource: impl Into<String>,
        ext: Extension,
        rand: impl Into<String>,
    ) -> Self {
        Self {
            ver,
            bits,
            date,
            resource: resource.into(),
            ext,
            rand: rand.into(),
            counter: String::from("0"),
        }
    }

    /// Returns ```true``` if hash has correct amount of zero bits
    pub fn check_hash(&self) -> bool {
        false
    }

    /// Stamp format version. Currently 1 is expected
    /// Fuck me if there is a new stamp format
    pub fn ver(&self) -> u8 {
        self.ver
    }

    /// Number of zero bits the hash has to start with.
    pub fn bits(&self) -> u8 {
        self.bits
    }

    /// ```YYMMDDhhmmss``` format date the stamp was created at. Used for expiry check
    pub fn date(&self) -> &Timestamp {
        &self.date
    }

    /// Resource the stamp is minted for
    pub fn resource(&self) -> &str {
        &self.resource
    }

    /// Extension field used by tollkeeper
    pub fn ext(&self) -> &Extension {
        &self.ext
    }

    /// string of random characters to avoid preimage attacks
    pub fn rand(&self) -> &str {
        &self.rand
    }

    /// string generated by user to get the required amount of bits
    pub fn counter(&self) -> &str {
        &self.counter
    }

    pub fn set_counter(&mut self, counter: impl Into<String>) {
        self.counter = counter.into();
    }
}

impl Display for Stamp {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let ver = &self.ver;
        let bits = &self.bits;
        let date = &self.date;
        let resource = &self.resource;
        let ext = &self.ext;
        let rand = &self.rand;
        let counter = &self.counter;
        write!(f, "{ver}:{bits}:{date}:{resource}:{ext}:{rand}:{counter}")
    }
}

struct Timestamp(chrono::DateTime<chrono::Utc>);
impl Display for Timestamp {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let date_str = self.0.format("%y%m%d%H%M%S");
        write!(f, "{date_str}")
    }
}
struct Extension(Vec<(String, String)>);
impl Display for Extension {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let ext_str = self
            .0
            .iter()
            .map(|e| format!("{}={}", e.0, e.1))
            .collect::<Vec<String>>()
            .join(";");
        write!(f, "{ext_str}")
    }
}
